version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres-test-container
    ports:
      - "5434:5432" # [port host : port container]
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
